/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectpembelian;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class HomePelangganFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomePelangganFrame
     */
    LoginFrame loginFrame;
    Date date = new Date();
    SimpleDateFormat simpleDate = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
    private static int count = 1;
    private static String tanggal;
    private static int total;
    private static String username;
    private static ArrayList<LinkedList<Object>> listProduk = new ArrayList<LinkedList<Object>>();
    private static ArrayList<LinkedList<Object>> listPembayaran = new ArrayList<LinkedList<Object>>();
    private static LinkedList<Object> currentUser = new LinkedList<Object>();
    
    public HomePelangganFrame() {
        initComponents();
        
        try{
            loginFrame = new LoginFrame();
            initVariables();
            addProdukToTable();
        }
        catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Anda harus login dahulu");
        }
        
    }
    
    public HomePelangganFrame(TambahProdukFrame tambahProduk){
        initComponents();
        try{
            this.listProduk.add(tambahProduk.getDetailProduk());
            addProdukToTable();
            textTanggal.setText(this.tanggal);
            textPelanggan.setText(this.username);
            textTotal.setText(Integer.toString(this.total));
        }
        catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Anda harus login dahulu");
        }
    }
   
    
    void initVariables(){
        this.currentUser = this.loginFrame.getCurrentUser();
        System.out.println(this.currentUser);
        this.username = (String) this.currentUser.get(1);
        this.tanggal = this.simpleDate.format(date);
        this.total = 0;
        
        textTanggal.setText(this.tanggal);
        textPelanggan.setText(this.username);
        textTotal.setText(Integer.toString(this.total));     
    }
    
    void addProdukToTable(){
        DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();
        Iterator value = listProduk.iterator();
        int i=0;
        while (value.hasNext()) {
            LinkedList<Object> temp = (LinkedList<Object>) value.next();
            temp.set(0, ++i);
            this.total = this.total + (int)temp.getLast();
            Object[] obj = temp.toArray();
            model.addRow(obj);
        }
        if(listProduk.isEmpty()){
            this.textTotal.setText(Integer.toString(0));
        }
        else{
            this.textTotal.setText(Integer.toString(this.total));
        }
        
    }
   
    ArrayList<LinkedList<Object>> getListPembayaran(){
        return this.listPembayaran;
    }
    
    ArrayList<LinkedList<Object>> getListProduk(){
        return this.listProduk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textTanggal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textPelanggan = new javax.swing.JTextField();
        buttonTambah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        textTotal = new javax.swing.JTextField();
        buttonBayar = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TANGGAL");

        textTanggal.setEditable(false);
        textTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTanggalActionPerformed(evt);
            }
        });

        jLabel2.setText("PELANGGAN");

        textPelanggan.setEditable(false);
        textPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPelangganActionPerformed(evt);
            }
        });

        buttonTambah.setText("TAMBAH");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonHapus.setText("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Produk", "Harga", "Jumlah", "SubTotal"
            }
        ));
        jScrollPane1.setViewportView(tableTransaksi);

        jLabel3.setText("TOTAL");

        textTotal.setEditable(false);
        textTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTotalActionPerformed(evt);
            }
        });

        buttonBayar.setText("BAYAR");
        buttonBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBayarActionPerformed(evt);
            }
        });

        buttonBatal.setText("BATAL");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonBayar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(buttonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textPelanggan))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonHapus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(buttonBayar)
                .addGap(18, 18, 18)
                .addComponent(buttonBatal)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        this.listProduk.clear();
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void textTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTanggalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textTanggalActionPerformed

    private void textPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPelangganActionPerformed

    private void textTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTotalActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
//        String data2 = "asa";
//        String data3 = "sasa";
//        String data4 = "1212";
//        Object[] row = { this.count++, data2, data3};
//        Object[] row = { nama, harga, jumlah, subtotal};
//
//        DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();
//
//        model.addRow(row);
//    System.out.println(this.tableTransaksi.getRowCount());
        new TambahProdukFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        try{
            
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (this, "Apakah anda akan menghapus Produk ini?","Warning",dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();
                int index = tableTransaksi.getSelectedRow();
                model.removeRow(tableTransaksi.getSelectedRow());
                listProduk.remove(index);
                JOptionPane.showMessageDialog(this, "Produk berhasil dihapus");
                new HomePelangganFrame().setVisible(true);
                dispose();
            }
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Tidak ada Produk yang dihapus");
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBayarActionPerformed
        // TODO add your handling code here:
        if(this.listProduk.isEmpty()){
            JOptionPane.showMessageDialog(this, "Silahkan tambahkan beberapa produk terlebih dahulu!");
        }else{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (this, "Apakah anda akan membayar?","Warning",dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                LinkedList<Object> detailTransaksi = new LinkedList<Object>();
                detailTransaksi.add(1);
                detailTransaksi.add(this.tanggal);
                detailTransaksi.add(this.username);
                detailTransaksi.add(this.total);
                
                this.listPembayaran.add(detailTransaksi);
                this.listProduk.clear();
                JOptionPane.showMessageDialog(this, "Silahkan ambil Nota dan ke Kasir. Terimakasih sudah berkunjung :D");
            }
        }
    }//GEN-LAST:event_buttonBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePelangganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePelangganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePelangganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePelangganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePelangganFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonBayar;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JTextField textPelanggan;
    private javax.swing.JTextField textTanggal;
    private javax.swing.JTextField textTotal;
    // End of variables declaration//GEN-END:variables
}
