/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectpembelian;

import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TambahProdukFrame extends javax.swing.JFrame {

    /**
     * Creates new form TambahProdukFrame
     */
    static HashMap<String, Integer> produk = new HashMap<String, Integer>();
    LinkedList<Object> detailProduk = new LinkedList<Object>();
    static private int hargaProduk;
    static private String namaProduk;
    static private int jumlahProduk;
    static private int subTotal;
    static private int count = 0;
    public TambahProdukFrame() {
        initComponents();
        initVariables();
    }
    
    public TambahProdukFrame(int sizeTable){
        
    }
    
    void initVariables(){
        this.cboxPilihProduk.addItem("Pilih Produk") ;
        
        this.produk.put("Agile Principle", 190000);
        this.produk.put("Clean Code Programming", 200000);
        this.produk.put("Design Paterns", 230000);
        this.produk.put("Object Oriented Design", 199000);
        
        String produk = null;
        Set entryProduk = getSetProduk();
        Iterator it = entryProduk.iterator();
        while(it.hasNext()){
            Map.Entry me = (Map.Entry) it.next();
            produk = (String) me.getKey();
            this.cboxPilihProduk.addItem(produk);
        }
    }
    
    public Set getSetProduk(){
        return this.produk.entrySet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboxPilihProduk = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        textJumlah = new javax.swing.JTextField();
        textHargaSatuan = new javax.swing.JTextField();
        textSubTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PILIH PRODUK");

        cboxPilihProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPilihProdukActionPerformed(evt);
            }
        });

        jLabel2.setText("HARGA SATUAN");

        jLabel3.setText("SUBTOTAL");

        jLabel4.setText("JUMLAH");

        buttonTambah.setText("TAMBAH");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonBatal.setText("BATAL");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        textJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJumlahActionPerformed(evt);
            }
        });

        textHargaSatuan.setEditable(false);

        textSubTotal.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxPilihProduk, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textHargaSatuan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textJumlah, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSubTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxPilihProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(textSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonTambah)
                .addGap(18, 18, 18)
                .addComponent(buttonBatal)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        try{
            if(this.cboxPilihProduk.getSelectedIndex()==0){
                throw new NullPointerException("Silahkan pilih Produk!");
            }
            if(this.jumlahProduk == 0){
                throw new NullPointerException("Silahkan inputkan jumlah produk!");
            }
            this.detailProduk.add(1);
            this.detailProduk.add(this.namaProduk);
            this.detailProduk.add(this.hargaProduk);
            this.detailProduk.add(this.jumlahProduk);
            this.detailProduk.add(this.subTotal);
            new HomePelangganFrame(this).setVisible(true);
            dispose();
        }catch(NullPointerException e){
             JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    LinkedList<Object> getDetailProduk(){
        return this.detailProduk;
    }
    
    private void textJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJumlahActionPerformed
        // TODO add your handling code here:
        try{
            this.jumlahProduk = Integer.parseInt(this.textJumlah.getText());
            this.subTotal = this.jumlahProduk * this.hargaProduk;
            this.textSubTotal.setText(Integer.toString(this.subTotal));
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Inputan jumlah berupa angka!");
        }
    }//GEN-LAST:event_textJumlahActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        new HomePelangganFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void cboxPilihProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPilihProdukActionPerformed
        // TODO add your handling code here:
        
        String produk = null;
        int harga = 0;
        Set entryProduk = getSetProduk();
        Iterator it = entryProduk.iterator();
        while(it.hasNext()){
            Map.Entry me = (Map.Entry) it.next();
            produk = (String) me.getKey();
            harga = (int) me.getValue();
            if(this.cboxPilihProduk.getSelectedIndex() != 0 
                    && this.cboxPilihProduk.getSelectedItem().equals(produk) ){
                this.textHargaSatuan.setText(Integer.toString(harga));
                this.hargaProduk = harga;
                this.namaProduk = produk;
                this.jumlahProduk = 1;
                this.subTotal = this.hargaProduk * this.jumlahProduk;
                this.textSubTotal.setText(Integer.toString(this.subTotal));
                this.textJumlah.setText(Integer.toString(this.jumlahProduk));
            }
//            this.cboxPilihProduk.addItem(produk);
        }
    }//GEN-LAST:event_cboxPilihProdukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahProdukFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JComboBox<String> cboxPilihProduk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textHargaSatuan;
    private javax.swing.JTextField textJumlah;
    private javax.swing.JTextField textSubTotal;
    // End of variables declaration//GEN-END:variables
}
